### ISSUE TITLE
How to enable 'BUILD_PYTHON' or have Python script in the right folder?

### ISSUE THREAD

**Issue by nikkolasedi** [ortegatron/hand_standalone#5]
nikkolas@nikkolas-X556UQK:~/hand_standalone-master$ python run.py
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    import detection_keypoints
  File "/home/nikkolas/hand_standalone-master/detection_keypoints.py", line 29, in <module>
    raise e
ImportError: No module named openpose

**Comment by MuserQuantity** [comment]
I recommend you read carefully the file “readme.md” in the project openpose and install it first correctly.
